export { Home } from './home'
export { About } from './about'
export { Contact } from './contact'
export { Resume } from './resume'
export { Experience } from './experience'
export { Projects } from './projects'
export { Publications } from './publications'